# Generated by Django 2.0.1 on 2018-01-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bucketlist',
            new_name='Questionlist',
        ),
    ]
