# Generated by Django 2.0.1 on 2018-01-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20180115_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlist',
            name='name',
        ),
        migrations.AddField(
            model_name='questionlist',
            name='predicate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='questionlist',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
